apiVersion: v1
kind: Service
metadata:
  name: jupyter
spec:
  type: LoadBalancer
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: jupyter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
spec:
  selector:
    matchLabels:
      app: jupyter
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/pyspark-notebook
        ports:
        - containerPort: 8888
        env:
        - name: SPARK_HOME
          value: "/usr/local/spark"
        volumeMounts:
        - name: notebooks-volume
          mountPath: /home/jovyan/work
      volumes:
      - name: notebooks-volume
        persistentVolumeClaim:
          claimName: notebooks-pvc
